name: pull_request

on:
  pull_request:
    branches:
      - '**' 
  
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true
  
defaults:
  run:
    shell: bash
    
jobs:
  build_and_upload:
    runs-on: 
      - ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - centos7
          - centos8
          - ubuntu2004
          - ubuntu2204
          - ubuntu2304
        arch:
          - ubuntu-latest
    container:
      image: vesoft/third-party-build:${{ matrix.os }}
    steps:
    - uses: webiny/action-post-run@3.0.0
      with:
        run: sh -c "find . -mindepth 1 -delete"
    - uses: actions/checkout@v3
    - name: Set up environment
      run: |
        echo "path=$(pwd)" >> $GITHUB_ENV
    - name: Pre-Build
      run: |
        cd ..
        if [ -d "build" ]; then
          find build -maxdepth 1 -mindepth 1 ! -name '*.tgz' -exec rm -rf {} +
        else
          mkdir build
        fi
        sync
    - name: Build    
      run: |
        build_package=1 ${{ env.path }}/build.sh
      working-directory: ../build/
      
    - name: Setup MinIO
      uses: vesoft-inc/.github/actions/setup-minio@master
      with:
        minio_url: ${{ secrets.MINIO_ENDPOINT }}
        access_key: ${{ secrets.MINIO_KEY }}
        secret_key: ${{ secrets.MINIO_SECRET }}
    - name: Copy dir to MinIO
      run: mc cp -r ../build/packages/ minio/pr-build/third-party/5.0/${{ github.event.pull_request.head.sha }}/

